sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  #- docker run gayanprasanna/docker-react npm run test -- --coverage
  - docker run stephengrider/docker-react npm run test -- --coverage
stephengrider/docker-reac
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env:  "DockerReact-env"
  bucket_name:  "elasticbeanstalk-us-east-1-608136487092"
  bucket_path:  "docker-react"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"